package com.example.gizo.advance.designsystem.theme
import androidx.compose.ui.graphics.Color

internal val md_theme_light_primary = Color(0xFF3E37FC)
internal val md_theme_light_onPrimary = Color(0xFFFFFFFF)
internal val md_theme_light_primaryContainer = Color(0xFFD8E2FF)
internal val md_theme_light_onPrimaryContainer = Color(0xFF001A41)
internal val md_theme_light_secondary = Color(0xFF565E71)
internal val md_theme_light_onSecondary = Color(0xFFFFFFFF)
internal val md_theme_light_secondaryContainer = Color(0xFFDBE2F9)
internal val md_theme_light_onSecondaryContainer = Color(0xFF393939)
internal val md_theme_light_tertiary = Color(0xFF715573)
internal val md_theme_light_onTertiary = Color(0xFFFFFFFF)
internal val md_theme_light_tertiaryContainer = Color(0xFFFBD7FC)
internal val md_theme_light_onTertiaryContainer = Color(0xFF29132D)
internal val md_theme_light_error = Color(0xFFBA1A1A)
internal val md_theme_light_errorContainer = Color(0xFFFFDAD6)
internal val md_theme_light_onError = Color(0xFFFFFFFF)
internal val md_theme_light_onErrorContainer = Color(0xFF410002)
internal val md_theme_light_background = Color(0xFFFEFBFF)
internal val md_theme_light_surfaceVariant = Color(0xFFE1E2EC)
internal val md_theme_light_onSurfaceVariant = Color(0xFF44474F)
internal val md_theme_light_outline = Color(0xFF74777F)
internal val md_theme_light_inverseOnSurface = Color(0xFFF2F0F4)
internal val md_theme_light_inverseSurface = Color(0xFF303033)
internal val md_theme_light_inversePrimary = Color(0xFFADC6FF)
internal val md_theme_light_surfaceTint = Color(0xFF007AFF)
internal val md_theme_light_outlineVariant = Color(0xFF1B2537)
internal val md_theme_light_scrim = Color(0xFF000000)

internal val md_theme_dark_surface = Color(0xFF1B1B1F)
internal val md_theme_dark_onSurface = Color(0xFFE3E2E6)
internal val redesignBackgroundColor = Color(0XFF0F172A)
internal val redesignRedColor = Color(0XFFF44336)
internal val redesignTextGray = Color(0xFF94A3B8)
